device: 'cuda:0' # 'cpu', 'cuda:0', 'cuda:1'
seed: 0
model:
  n_timesteps: 40 # Number of time steps T
  diffusion_schedule:
    name: 'linear' # 'linear'
    slope: 0.36
  n_backward_layers: 6 # L
  n_ancilla_qubits: 2 # na
training:
  overwrite_saves: True
  batch_size: null # If null, it will be set to the size of the training dataset
  n_epochs: 5001 # Epochs for training each time step
  learning_rate: 0.005
  lr_scheduler: 
    type: 'CosineAnnealingWarmRestarts' # 'CosineAnnealingWarmRestarts', 'ctt',
    T_0: 50
    T_mult: 2
  regularization: 0.03
  live_plot:
    save: True
    frequency: 50
  loss_fn: 'sinkhorn' # 'sinkhorn', 'wass'
dataset:
  dir: 'data' # Directory to store the dataset
  name: 'CIRCLEY_3' # e.g. 'MNIST_0', 'CIRCLEY_3'
  # transforms:
  #   resize: 16 # nxn pixels to resize.
  maxsize: 1000
  
