seed: 0
savedir: results/TimeConditionedMLP/CIRCLEY_1/nhidden10_hiddendim16
device: cuda:0
model:
  n_timesteps: 20
  params:
    input_dim: 4
    output_dim: 4
    hidden_dim: 16
    n_hidden_layers: 10
    time_embed_dim: 20 # D, not need to match anything.
    time_base: 100 # B, Nor this.
  activation: ReLU
  diffusion_schedule: 
    'name': 'linear'
    'slope': 6
training:
  avg_val_loss_goal: 0.01
  save_interval: 2000
  learning_rate: 1e-4
dataset:
  name: CIRCLEY_1
  n_data: 200
  batch_size: 100
  n_features: 2
diffusion:
  n_timesteps: 20